from pydantic import BaseModel, Field
from typing import Optional, List
from datetime import date

# ===== NESTED MODELS =====

class Dependant(BaseModel):
    """Section 2: Dependants' details"""
    id: Optional[int] = None  # Auto-generated by DB
    claim_id: str
    name: str
    relationship: str

class AccidentDetails(BaseModel):
    """Section 4: Accident information"""
    id: Optional[int] = None
    claim_id: str
    description: str
    accident_date: date
    expenses_recoverable: bool
    claiming_through_solicitor: bool = False
    claiming_through_piab: bool = False
    third_party_policy_details: Optional[str] = None
    member_signed: bool = False
    subscriber_signed: bool = False

class PaymentDetails(BaseModel):
    """Section 7: Bank account info"""
    id: Optional[int] = None
    claim_id: str
    use_existing_direct_debit: bool = False
    account_holder_name: Optional[str] = None
    account_number: Optional[str] = None
    bank_sort_code: Optional[str] = None
    bank_name_and_address: Optional[str] = None
    signature_date: Optional[date] = None
    is_signed: bool = False

class ReceiptItem(BaseModel):
    """Section 6: Individual receipt line items"""
    id: Optional[int] = None
    claim_id: str
    treatment_type: str  # e.g., "GP Visit", "Physiotherapy"
    receipt_date: date
    cost: float

# ===== MAIN CLAIM MODEL =====

class ClaimForm(BaseModel):
    """
    Complete Laya Out-patient Claim Form
    (Master record with nested children)
    """
    # Core Identity
    claim_id: str  # Primary Key (e.g., "CLM-2025-003")
    membership_number: str
    
    # Section 1: Member Details
    title: Optional[str] = None
    surname: str
    forenames: str
    date_of_birth: date
    telephone: Optional[str] = None
    correspondence_address: str
    
    # Processing Metadata
    submission_date: date
    status: str = "PENDING"  # PENDING, APPROVED, REJECTED, REQUIRES_INFO
    assessed_amount: Optional[float] = None
    rejection_reason: Optional[str] = None
    
    # Nested Collections (Populated separately)
    dependants: List[Dependant] = []
    accident_details: Optional[AccidentDetails] = None
    payment_details: Optional[PaymentDetails] = None
    receipt_items: List[ReceiptItem] = []

    class Config:
        from_attributes = True
